# This is used to compile for x86_64 system on apple silicon devices
services:
  box:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    command: > 
      bash -c "echo 'Copy complete. Container started...' &&
      tail -f /dev/null"
    working_dir: /app
    environment:
      - PATH=/libs/jai/bin:$PATH
    volumes:
      - "./:/app"
      # Hardcoding the value, but oh well!!! Jai is in closed beta
      - "${HOME}/seg4ltcode/seg4lt-libs/jai:/libs/jai"
